### ISSUE TITLE
Making utilities available by default

### ISSUE THREAD

**Issue by zhubonan** [conda-forge/airss-feedstock#1]
### Comment:

First, nice to see this on conda-forge and great work! @awvwgk

It seems that the default package only exposes an `airss` executable. However, normally other tools such as `buildcell`, `cabal` and `cryan` are also needed by the user for basic operations. This is rather expected - for example, one cannot run the examples that come with the source distribution with the `airss` conda-forge package. 

Perhaps it is better to have the `airss-with-default-names` as the default, and rename `airss` (as for now) to something like `airss-runtime` for example?

**Comment by awvwgk** [comment]
Thanks for the suggestion, in the package review there were concerns for adding lots of small executables and scripts to the conda prefix by default, hence the wrapper script and an opt-in variant of the default package. The alternative you suggested would use an opt-out mechanism, but in this case I think it wouldn't make sense to split the package at all.

**Comment by awvwgk** [comment]
The relevant thread can be found at https://github.com/conda-forge/staged-recipes/pull/22001#discussion_r1112397717

**Comment by zhubonan** [comment]
Ah I see, that makes sense! 

I had a go for making a conda package for AIRSS in the past, which was mainly for easy installation in CI workflows. 

As a heavy user, I still think a few tools should be made available even in the default, while many other scripts are primarily only used with the `airss.pl` script. 

For example:

- `buildcell` - useful for testing if the input seed can be build
- `cryan` - for analysing results
- `cabal` - for converting the structures

There is also a typo where `build_cell` should be `buildcell` in `airss-bin.txt`.

**Comment by awvwgk** [comment]
Thanks for the feedback. If you like please submit a patch for those changes and feel free to add yourself as maintainer.

**Comment by zhubonan** [comment]
Closing the issue as it has been addressed in #2.
@awvwgk Thanks for the quick response! 🎊🎊
